server:
    port: 8090

spring:
    application:
        name: spring-order-service1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5